import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'

import './global.css'

import type { ReactNode } from 'react'
import type { NextPage } from 'next'

export const metadata = {
  title: 'Welcome to host',
  description: 'Generated by create-nx-workspace',
}

type RootLayoutProps = {
  children: ReactNode
}

const RootLayout: NextPage<RootLayoutProps> = ({ children }) => (
  <html lang="en" suppressHydrationWarning>
    <head>
      <ColorSchemeScript />
    </head>
    <body>
      <MantineProvider>{children}</MantineProvider>
    </body>
  </html>
)
export default RootLayout
